name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 设置超时时间

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt update
        # Install main dependencies
        sudo apt install -y \
          git zip unzip openjdk-11-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev \
          cmake libffi-dev libssl-dev

        # Handle libtinfo5 compatibility for Ubuntu 24.04
        if ! sudo apt install -y libtinfo5 2>/dev/null; then
          echo "libtinfo5 not available, installing libtinfo6 and creating symlink"
          sudo apt install -y libtinfo6
          # Create compatibility symlink for libtinfo5
          sudo ln -sf /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5 || true
        fi

        # Install additional dependencies that might be needed
        sudo apt install -y \
          build-essential \
          libffi-dev \
          libssl-dev \
          python3-dev \
          python3-setuptools

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 30
        build-tools: 30.0.3
        ndk-version: 25.2.9519653

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install dependencies with specific versions for better compatibility
        pip install --upgrade setuptools wheel
        pip install buildozer cython==0.29.36 kivy[base]==2.1.0

        # Verify installations
        python -c "import kivy; print(f'Kivy version: {kivy.__version__}')"
        buildozer --version

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Build APK with Buildozer
      run: |
        # Set up environment variables
        export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
        export ANDROID_HOME=$ANDROID_HOME
        export ANDROID_NDK_HOME=$ANDROID_NDK_HOME
        export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools

        # Show environment info for debugging
        echo "Android SDK Root: $ANDROID_SDK_ROOT"
        echo "Android Home: $ANDROID_HOME"
        echo "Android NDK Home: $ANDROID_NDK_HOME"
        echo "Java Home: $JAVA_HOME"

        # Initialize buildozer if needed
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

        # Build the APK
        buildozer android debug
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: pushup-counter-debug-apk
        path: bin/*.apk
        retention-days: 30

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: .buildozer/android/platform/build-*/
        retention-days: 7
